### ISSUE TITLE
Check translation exists before using it

### ISSUE THREAD

**Issue by juliovedovatto** [sveltekit-i18n/lib#105]
I'm working with some dynamic content to retrieve a key to translate.

```svelte
<script lang="ts">
   import { t } from '@lib/translations';

   $: key = `content.datasheet.${title.toLowerCase()}`
</script>

<span class="uppercase">{$t(key)}</span>
```

I would like to test if translation exists before using it, so I can use a custom fallback instead `fallbackValue` property.

I was envisioning something like this:

```svelte
<script  lang="ts">
  import { t } from '@lib/translations';
  
   $: key = `content.datasheet.${title.toLowerCase()}`
</script>

<span class="uppercase">{t.exists(key) ? $t(key) : title}</span>
```

To achieve desired output, I ended up creating a custom function.

```ts
// translations/index.ts

export const { t, l, loading, locales, locale, loadTranslations, translations } = new i18n(config);

export const te = (key: string, payload: Record<string, string> = {}) => {
	return t.get(key, payload) !== key;
};
```

```svelte
<script lang="ts">
  import { t, te } from '@lib/translations';

  const translateDatasheetTitle = (title: string) => {
    const key = `content.datasheet.${title.toLowerCase()}`;
    return te(key) ? $t(key) : title;
  };
</script>

<span class="uppercase">{translateDatasheetTitle(title)}</span>

```

Is there a better way to accomplish that @jarda-svoboda ?

**Comment by jarda-svoboda** [comment]
Hi @juliovedovatto, sorry for my later response. Yes, with the default parser, there is a `default` prop (documented [here](https://github.com/sveltekit-i18n/parsers/tree/master/parser-default#placeholders)).  The `default` value replaces the key in case there is no translation for the given key..
```js
$t('undefined.key', { default: 'Default value' });
```

**Comment by jarda-svoboda** [comment]
Oh, sorry, the link to the docs is wrong. This behavior is not documented.. I’m adding it..
