### ISSUE TITLE
Non-standard locale provided warning (mn case)

### ISSUE THREAD

**Issue by mckabi** [sveltekit-i18n/lib#109]
(It does not duplicate #75)

I received the following warning:
> [18n]: Non-standard locale provided: 'mn'. Check your 'translations' and 'loaders' in i18n config...

'mn' is Mongolian (Монгол) which is also in the IANA Language subtag registry

```js
  // base/src/utils.ts
  return locales.filter((locale) => !!locale).map((locale) => {
    let current = `${locale}`.toLowerCase();
    try {
      const [sanitized] = Intl.Collator.supportedLocalesOf(locale);

      if (!sanitized) throw new Error(`'${locale}' is non-standard.`);

      current = sanitized;
    } catch (error) {
      logger.warn(`Non-standard locale provided: '${locale}'. Check your 'translations' and 'loaders' in i18n config...`);
    }

    return current;
  });
```

```js
Intl.Collator.supportedLocalesOf(['mn', 'ko', 'en'])
// ['ko', 'en'] :-(
```

**Comment by arnthor3** [comment]
I had the same problem with `is`, I used a noop for console.warn on prod to remove this. 

```javascript
if (process.env.NODE_ENV === 'production') {
 console.warn = () => {}
}
```

**Comment by jarda-svoboda** [comment]
As far as the `mn` locale is not supported by `Intl.Collator.supportedLocalesOf` you could avoid console warnings for production like this:

```ts
import type { Config } from 'sveltekit-i18n';

const config: Config = {
  // ...
  log: {
    level: process.env.NODE_ENV === 'production' ? 'error' : 'warn',
  }
};

```

**Comment by baisong** [comment]
Hello, thank you @jarda-svoboda for this solution.

Where is the recommended place to add this warning suppression configuration? Just once, inside `/src/lib/translations/index.js`?

Is there anything different recommended for non-typescript implementation?

**Comment by jarda-svoboda** [comment]
Hi @baisong!

Yes, the right place to avoid warning logs is `log` setting in your config.

There is no difference in comparison to typescript.
