### ISSUE TITLE
Not ready for Svelte 4.0

### ISSUE THREAD

**Issue by juanjoseluisgarcia** [sveltekit-i18n/lib#113]
This package will not run on Svelte 4.0 and Sveltekit 1.20

**Comment by jarda-svoboda** [comment]
As a workaround (until the new version of this library is released) you could use `—force` flag - technically the library works with svelte 4, but its peer dependencies are now limited to version 3..
```
npm install svelte@4 —force
```

**Comment by juanjoseluisgarcia** [comment]
> As a workaround (until the new version of this library is released) you could use `—force` flag - technically the library works with svelte 4, but its peer dependencies are now limited to version 3..
> 
> ```
> npm install svelte@4 —force
> ```

Yes, This is what I have been doing so far. Also every time you upgrade to the latest packages needs the `--force` flag.
