### ISSUE TITLE
Default locale flashes when reloading page

### ISSUE THREAD

**Issue by MvRemmerden** [sveltekit-i18n/lib#153]
When I reload the multi-page example on Netlify, the dropdown menu for selecting the locale flashes the default value. 

I'm having the same problem when developing locally, and while the normal translated text is displayed perfectly fine without flashing, I couldn't figure out how to remove the flashing for the locale.

![Kapture 2023-10-03 at 21 07 45](https://github.com/sveltekit-i18n/lib/assets/18680169/a496cf14-76b1-4659-a142-3c632bd77e4f)

**Comment by jarda-svoboda** [comment]
Hi @MvRemmerden!
I’m not 100% sure, but I think this one is about browser’s behavior - how it deals with preselected options in select component. For instance, I see no glitches in Safari on iOS.

https://github.com/sveltekit-i18n/lib/assets/20700514/53ed536c-c198-4f5f-a473-8022e23d1969

**Comment by jarda-svoboda** [comment]
Actually you could use `selected` attribute (e.g. `selected="{$locale === value}"`) to get rid of this behavior.. it seems that `bind:value` does not handle it by default..

**Comment by jarda-svoboda** [comment]
Fixed in the [example](https://github.com/sveltekit-i18n/lib/blob/9e1b173633a24089206445eedbf63519bd749e0e/examples/multi-page/src/routes/%2Blayout.svelte#L28)
