### ISSUE TITLE
Adding log when no translation is found in provided local/fallback

### ISSUE THREAD

**Issue by ThibaultAndreis** [sveltekit-i18n/lib#154]
I think it would be useful to have logs specifying which translation is missing.

Currently, if no translation is found, no log specifies if it's missing from the provided locale and/or fallback.

I've made a  [pull request](https://github.com/sveltekit-i18n/base/pull/13) in sveltekit-i18n/base to propose small changes that would add them.

**Comment by Skylli202** [comment]
I think that would be helpful. I've had an unpleasant time recently trying to find which translation were missing.

**Comment by ThibaultAndreis** [comment]
I can change that
Should we then add a warn if no tranlsation nor fallback value is found ?

like so :
```javascript
if (text === undefined) {
    logger.debug(`No translation provided for '${key}' key in fallback '${fallbackLocale}'.`);
    if (rest.hasOwnProperty('fallbackValue')  ) {
      return rest.fallbackValue;
    }
    logger.warn(`No translation nor fallback found for '${key}' .`);
  }
```

**Comment by ThibaultAndreis** [comment]
i've made the changes to my PR

**Comment by jarda-svoboda** [comment]
Deployed 🚀
