### ISSUE TITLE
'cy' locale is non-standard.

### ISSUE THREAD

**Issue by DominikKoller** [sveltekit-i18n/lib#158]
I am getting the warnings:

'cy' locale is non-standard.
'is' locale is non-standard.
'ne' locale is non-standard.
'pa' locale is non-standard.

When providing these locales in Config.translations. I tried 'cy-GB', 'is-IS', 'ne-NP', 'pa-IN' as well, which give me the same warning.

They are standard locales according to ISO:
https://www.w3schools.com/tags/ref_language_codes.asp

**Comment by jarda-svoboda** [comment]
Hi @DominikKoller! Feel free to read more about this behavior [here](https://github.com/sveltekit-i18n/lib/issues/156). 
Closing as a duplicate..
