### ISSUE TITLE
Dynamic translations inside each

### ISSUE THREAD

**Issue by timoanttila** [sveltekit-i18n/lib#159]
This module seems perfect for my case, but I am wondering if there is support for dynamic translations like the code below. I have data in the database that has only keywords because those labels need to be translated. The data is in JSON format in one field, and there are 41 values, so I would not like to add them one by one to the Svelte code.

Is there a way to use `sveltekit-i18n` for dynamic translations? I have all the keys and values in a JSON file.

```
  {#each data.scores as score}
    <div>
      <div>{$t(`results.${score.key}`)}</div>
      <div class="text-2xl">{score.value}</div>
    </div>
  {/each}
```

I can do this with [svelte-i18n](https://www.npmjs.com/package/svelte-i18n):

```
<script lang="ts">
  import {_} from 'svelte-i18n'

  const content = ['payment', 'account', 'multiple_websites', 'why']
</script>

{#each content as item}
  <details>
    <summary>{$_(`faq.${item}_question`)}</summary>
    <div>{$_(`faq.${item}_answer`)}</div>
  </details>
{/each}
```

**Comment by jarda-svoboda** [comment]
Hi @timoanttila!
I’m not sure what exactly you are looking for - translations in loops should work normally. For more information, check out [parser-default](https://github.com/sveltekit-i18n/lib/tree/master/examples/parser-default) and [preprocess](https://github.com/sveltekit-i18n/lib/tree/master/examples/preprocess) examples. Hope it’ll help.)

**Comment by timoanttila** [comment]
I had some problems with test results before, but now I tried dynamic values for the price list, and that seems to be working fine. Thank you, and sorry about this.

**Comment by jarda-svoboda** [comment]
Np😉
