### ISSUE TITLE
Error with Svelte 5.0.0, can't install package.

### ISSUE THREAD

**Issue by extechhost** [sveltekit-i18n/lib#161]
% npm i sveltekit-i18n
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: odm@0.0.1
npm ERR! Found: svelte@5.0.0-next.25
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^5.0.0-next.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@">=3.49.0" from sveltekit-i18n@2.4.2
npm ERR! node_modules/sveltekit-i18n
npm ERR!   sveltekit-i18n@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by jarda-svoboda** [comment]
I guess you could force update for now, but I’ll update the peer dependency and release a new version soon.

**Comment by jarda-svoboda** [comment]
Looked into this today and it should start working normally after `svelte@5` is a stable release. For pre-releases, please, use `--force` or `--legacy-peer-deps`.
