### ISSUE TITLE
Support for  ICU MessageFormat?

### ISSUE THREAD

**Issue by chosecz** [sveltekit-i18n/lib#28]
Can you support ICU message format? Like:
"{n, plural, =0 {Žádné notifikace} one {# notifikace} few {# notifikace} other {# notifikací}}"
"{showResources, select, true {Skrýt} other {Zobrazit} } dokumenty"

https://unicode-org.github.io/icu/userguide/format_parse/messages/

We are using this format in our projects and I would love to use your library...

**Comment by jarda-svoboda** [comment]
Well, when I started with this project, ICU was one of possible ways, but I decided not using it and provide my own solution. My goal is to provide as tiny library as possible - with basic functionality (but extendable using [Custom modifiers](https://github.com/jarda-svoboda/sveltekit-i18n/tree/master/examples/custom-modifiers)). In most cases, this library is used as a production dependency so my point was to use a lightweight solution. 
On the other hand, this may not fit all. In the next major release I would like to make this lib more granular and exclude parser to separate library. In that case you could use any parser you want installing a parser of your choice..

**Comment by jarda-svoboda** [comment]
Ok, currently used parser [excluded to separate folder](https://github.com/jarda-svoboda/sveltekit-i18n/tree/master/src), which is the first step on a way to custom parsers..

**Comment by chosecz** [comment]
Perfect, thanks

**Comment by jarda-svoboda** [comment]
`@sveltekit-i18n/parser-icu@1.0.0-rc.0` published
