### ISSUE TITLE
html lang parameter not changes when switch language

### ISSUE THREAD

**Issue by oratoran** [sveltekit-i18n/lib#30]
Hi,

`<html lang="en">` 
persistance when you change language. any easy fix?

thanks

**Comment by jarda-svoboda** [comment]
As far as I know, SvelteKit currently does not provide a simple solution for this (yet). So you could use [this workaround]( https://github.com/sveltekit-i18n/lib/blob/master/examples/locale-router/src/hooks.js#L31-L35) using SvelteKit `hooks`...
