### ISSUE TITLE
concurrent requests will lead to inconsistent `$t` store

### ISSUE THREAD

**Issue by ivanhofer** [sveltekit-i18n/lib#32]
Hey, I just stumbled accross your library and I think you will have the same problem like I had with my i18n library [`typesafe-i18n`](https://github.com/ivanhofer/typesafe-i18n).

When having multiple parallel requests, the store could change before the first request is completed, leading in a wrong locale beeing rendered. See here for more details: https://github.com/ivanhofer/typesafe-i18n/issues/159

I want to replicate it using one of your examples, but I could not install the `sveltekit-i18n` dependencies. I think something is currently broken...

**Comment by jarda-svoboda** [comment]
Hi:) Currently is version 2 still under development and its dependencies (base+parser) are probably set wrong to (unreleased yet) `@^1.x`. Their actual version is `@1.0.0-rc.0`. I need to fix this up in examples.
 Alternatively, you could try on [sveltekit-i18n@1.x](https://github.com/sveltekit-i18n/lib/tree/1.x/examples#how-to) - loader logic behind is more less the same, but don’t try to understand types there - they’re chaos-based..😅

`typesafe-i18n` is cool anyway! I wish I would have more free time to dive in it more deeply.)

**Comment by jarda-svoboda** [comment]
Oh, and to the point - this should not happen with this lib, I think..

**Comment by ivanhofer** [comment]
I`ll try it sometime this week 👍

I'm pretty confident that this will also affect your library since it works similar to `typesafe-i18n`

**Comment by ivanhofer** [comment]
It seems you are solving the same problems with `sveltekit-i18n` like I do with `typesafe-i18n`.
What are your long-running plans for this library?
Any interests in joining forces to create the best possible i18n solution for sveltekit projects?

**Comment by jarda-svoboda** [comment]
Yeah, It would make sense... I'll text you.

**Comment by jarda-svoboda** [comment]
OK, no change in the library needed. The only difference is in the initialization...

```svelte
<script context="module">
  import {setLocale, locale} from '$lib/test';

  /** @type {import('@sveltejs/kit').Load} */
  export const load = async ({ params }) => {
    const initLocale = `${params.locale}`;
    
    await loadTranslations(initLocale, '/');

    await new Promise((res) => setTimeout(res, 5000));

   locale.set(`${initLocale}`); // <== this will set the correct locale for SSR

    return {}
  }
</script>
```

I'll update it in examples. This solution seems to me as sufficient with minimal affect to the initial process...

**Comment by jarda-svoboda** [comment]
Hah, cool:D
