### ISSUE TITLE
default language ignored

### ISSUE THREAD

**Issue by ralyodio** [sveltekit-i18n/lib#35]
I changed default language in firefox from English to German and i'm still only seeing english translations.

I checked `navigator.language` in console and it correclty says `de`

**Comment by jarda-svoboda** [comment]
Regarding to `navigator.language` - you have to implement the initialization of that locale in your app… This approach does not necessarily fit to everyone, so setting the initial locale is completely in developer's hands…

**Comment by ralyodio** [comment]
yeah, so i want to get the default locale from the browser but when I use `navigator` it's undefined....how else would I get it?

**Comment by jarda-svoboda** [comment]
You can get it using `navigator` but only on client side. You could use Svelte's `browser` env to find out if you’re initializing on client or server. And for server use for example accepts-language http header, but it can lead to different language outputs as you are using two different sources.. 
Another way is to use a different approach which works for both of the sides, like cookie or locale in url path.
