### ISSUE TITLE
what is       key: 'common', used for?

### ISSUE THREAD

**Issue by ralyodio** [sveltekit-i18n/lib#36]
Is it reuqired? I don't see it used for anything.

I have  a simple /lang/en.json with key/value json object....but its not working all that `t('foo')` shows it the key, not a value from lang file.

**Comment by ralyodio** [comment]
also what is this `.default`? is that required? I tried removing, same issue.

**Comment by ralyodio** [comment]
Here is a sample lang file:

```
{
    "Welcome": "Welcome2"
}
```

this is in `$lib/lang/en.json`

**Comment by jarda-svoboda** [comment]
Keys are namespace specific identifiers so loader knows whether translation is already loaded or not.

For example this translation…
```jsonc
// en.json / es.json / de.json / …

{
    "welcome": "Welcome home!"
}
```

…with this config…
```js
const config = ({
  loaders: [
    {
      locale: 'en',
      key: 'keyname',
      loader: async () => (
        await import('./lang/en.json')
      ).default,
    },
    {
      locale: 'es',
       key: 'keyname',
      loader: async () => (
        await import('./lang/es.json')
      ).default,
    },
    {
      locale: 'de',
       key: 'keyname',
      loader: async () => (
        await import('./lang/de.json')
      ).default,
    },
  ],
});
```

…results in:
```js
$t('keyname.welcome’);
// Welcome home
```

This approach is useful when you are loading your translations by page..

For example:
```js
const config = ({
  loaders: [
    {
      locale: 'en',
      key: 'home',
      routes: ['/'],
      loader: async () => (
        await import('./en/home.json')
      ).default,
    },
    {
      locale: 'en',
      key: 'about',
      routes: ['/about'],
      loader: async () => (
        await import('./en/about.json')
      ).default,
    },
    // …
}
```

The `.default` depends on your `allowSyntheticDefaultImports` config in your js/tsconfig. So it’s not necessary in every case.

Hope this helped.) See [Examples](https://github.com/sveltekit-i18n/lib/tree/master/examples) and [Docs](https://github.com/sveltekit-i18n/lib/blob/master/docs/README.md) for more.

**Comment by ralyodio** [comment]
I don't want to use a namespace. Its unintiuitve best is to use english word as key....can i disable this or ignore it?

If I remove "key" it doesn't work

**Comment by ralyodio** [comment]
SO I used `key: ''` and it seems to work, however `navigator` is not available inside module so your exmaple simply won't work in real life.

I moved the logic to `beforeUpdate()` and it works but I get a flash of english before it switches to german....not sure how to fix this.

**Comment by jarda-svoboda** [comment]
Well, maybe you could use [`translations`](https://github.com/sveltekit-i18n/lib/blob/master/docs/README.md#config) instead of `loaders` as you need all your translations in place and don’t want to bother with loading your translations per-page..

The flash is there, because you have SSR turned on. In that case:
1) Svelte renders first on server, where it does not have access to your `navigator`, so it uses your default language setting
2) after this happens, page is sent to client where you are triggering the change.

**Comment by ralyodio** [comment]
I moved it to onMount and flash went away. 

What do you mean by “not using a loader”?

**Comment by jarda-svoboda** [comment]
See [this example](https://github.com/sveltekit-i18n/lib/tree/master/examples/single-load) you can provide all translations directly without using `loaders` in config...
