### ISSUE TITLE
Routes bug

### ISSUE THREAD

**Issue by Tazi0** [sveltekit-i18n/lib#41]
We currently have pages like so: `…/en/about`. But the routes located in the configuration either doesn’t work like `/about` or `/en/about`. Is there a possible fix for this?

The current homepage `/en` also doesn’t work with the i18n routes exampled here: `routes: ['/','en','/en/','/en']`

**Comment by jarda-svoboda** [comment]
Hi @Tazi0 have you tried to setup your app like [this](https://github.com/sveltekit-i18n/lib/tree/master/examples/locale-router)?

**Comment by jarda-svoboda** [comment]
Closing as stale..
