### ISSUE TITLE
[Request] Remove non-error console logs in production

### ISSUE THREAD

**Issue by PeterNjeim** [sveltekit-i18n/lib#42]
Hello, I get this message in my console: "[i18n]: Promises has been purged.", (which has a grammatical error lol, should be "have" not "has") from here: https://github.com/sveltekit-i18n/base/blob/2cd00c8aa9f9d2549d4f514aee2e73c1edc24e5c/src/index.ts#L23. Is there a way to disable this? Maybe a toggle for the release build? Not a big deal at all, but I like to keep my console clean if all is running smoothly.

**Comment by jarda-svoboda** [comment]
Hah, sure!😂

**Comment by jarda-svoboda** [comment]
@PeterNjeim `2.1.1` released!
