### ISSUE TITLE
is the lib prepared to deal with translations of numbers and dates?

### ISSUE THREAD

**Issue by juanjo** [sveltekit-i18n/lib#43]
I have been trying your lib, and it works really nice. Thank you.
I need to translate the format of dates and numbers (currency), is it the library prepared?
Do you have at hand any example how to do so with this lib?

For example:
```
<div>{$number(100000000)}</div>
<!-- 100,000,000 -->

<div>{$number(100000000, { locale: 'pt' })}</div>
<!-- 100.000.000 -->
```

Thank you in advance,
J.

**Comment by jarda-svoboda** [comment]
hi @juanjo – sure.) see `number` or `date` modifier in [this example](https://github.com/sveltekit-i18n/lib/tree/master/examples/parser-default)
