### ISSUE TITLE
Locale contains _ error

### ISSUE THREAD

**Issue by muzidudu** [sveltekit-i18n/lib#45]
i use [https://github.com/sveltekit-i18n/lib/tree/master/examples/locale-router](https://github.com/sveltekit-i18n/lib/tree/master/examples/locale-router)

if change       `[current] = Intl.Collator.supportedLocalesOf(locale.replace('_','-'));`
https://github.com/sveltekit-i18n/base/blob/272effd898f92888fc17b5735f3317ef067e1cc4/src/utils.ts#L32
I hope to modify here will not prompt an error

**Comment by jarda-svoboda** [comment]
hi @muzidudu
if i understand it correctly, the problem is, that in case you use a non-standardized locale it throws an error? that's desired behavior anyway, because this locale can be used later in html `lang` attribute etc., so it should be in standardized form...

**Comment by muzidudu** [comment]
> hi @muzidudu if i understand it correctly, the problem is, that in case you use a non-standardized locale it throws an error? that's desired behavior anyway, because this locale can be used later in html `lang` attribute etc., so it should be in [standardized](https://www.w3schools.com/tags/ref_language_codes.asp) form...

but i set `zh-Hans`  Prompt error as usual

**Comment by jarda-svoboda** [comment]
…also relevant tests should be added…

**Comment by jarda-svoboda** [comment]
@muzidudu  Ok, there is probably nothing wrong about the base. It's a bug in the [url parer](https://github.com/sveltekit-i18n/lib/blob/841667d982714dc6cbe616feed8c9f487115c1d5/examples/locale-router/src/routes/__layout.svelte#L8)...

**Comment by jarda-svoboda** [comment]
[example fixed](https://github.com/sveltekit-i18n/lib/commit/4245e4d0c58d213133653fff9108946b22437e92)
