### ISSUE TITLE
No translation key or locale provided. Skipping translation...

### ISSUE THREAD

**Issue by sc00** [sveltekit-i18n/lib#46]
Hi,

I've been using sveltekit-i18n successfully today. After adding two lines of unrelated code the app wouldn't translate anymore with the following error:

No translation key or locale provided. Skipping translation...

Commenting out the new code didn't solve the problem. Reinstalling the package didn't either. I even replaced all the translation related code with the one provided in the README with no success.

Other than the i18n package the app is still empty. What can this error mean?

Thanks

**Comment by jarda-svoboda** [comment]
hi.)
this seems weird to me... have you tried to startup with some of [examples](https://github.com/sveltekit-i18n/lib/tree/master/examples)?
if you are still facing difficulties, could you please provide a repro? thanks!.)

**Comment by dewrano** [comment]
@jarda-svoboda I get this warning when I don't provide an English locale. Example:

No warning:

`import i18n from 'sveltekit-i18n';

/** @type {import('sveltekit-i18n').Config} */
const config = ({
  loaders: [
    {
      locale: 'en',
      key: 'home',
      loader: async () => (
        await import('./en/home.json')
      ).default,
    },
    {
      locale: 'it',
      key: 'home',
      loader: async () => (
        await import('./it/home.json')
      ).default,
    },
  ],
});

export const { t, locale, locales, loading, loadTranslations } = new i18n(config);`

Warning:

`import i18n from 'sveltekit-i18n';

/** @type {import('sveltekit-i18n').Config} */
const config = ({
  loaders: [
    {
      locale: 'de',
      key: 'home',
      loader: async () => (
        await import('./de/home.json')
      ).default,
    },
    {
      locale: 'it',
      key: 'home',
      loader: async () => (
        await import('./it/home.json')
      ).default,
    },
  ],
});

export const { t, locale, locales, loading, loadTranslations } = new i18n(config);`

Why?

**Comment by jarda-svoboda** [comment]
Closing as stale.. please let me know if the issue persists (incl. the repro).. thanks!

**Comment by MirkoR89** [comment]
Hi,

I have the same problem.
I tried to install and use sveltekit-i18n for 3 time but I always had this problem.

`No translation key or locale provided. Skipping translation...`

I also followed the example that I found in the docs (multi-page) but the translation didn't work.
Could you please help me?

I attach the link of my [repo](https://github.com/MirkoR89/vite-sveltekit-tailwind-portfolio). It's a little project that I just started. You can find the file in _translation.js_ following the path _src/lib/translation_  and the test in the file _+about.svelte_ following the path _src/routes/about_

Thank you

**Comment by aakash14goplani** [comment]
> Hi,
> 
> I have the same problem. I tried to install and use sveltekit-i18n for 3 time but I always had this problem.
> 
> `No translation key or locale provided. Skipping translation...`
> 
> I also followed the example that I found in the docs (multi-page) but the translation didn't work. Could you please help me?
> 
> I attach the link of my [repo](https://github.com/MirkoR89/vite-sveltekit-tailwind-portfolio). It's a little project that I just started. You can find the file in _translation.js_ following the path _src/lib/translation_ and the test in the file _+about.svelte_ following the path _src/routes/about_
> 
> Thank you

Were you able to find solution? I am Facing same issue!

**Comment by jarda-svoboda** [comment]
Hi guys, I tried to run @MirkoR89's repo today, but i'm not getting the warning for his example.. In most cases this warning is about wrong implementation of this library. Also, you could try to update to the newest version where this warning is a bit more concrete about keys and locales..

**Comment by aakash14goplani** [comment]
For the folks looking for resolution of error, I was able to solve this error by fixing code flow in layout.server.ts, layout.ts and translations.ts file as given in the example for [component-scoped-ssr](https://github.com/sveltekit-i18n/lib/tree/master/examples/component-scoped-ssr)

**Comment by nickgayo12** [comment]
> For the folks looking for resolution of error, I was able to solve this error by fixing code flow in layout.server.ts, layout.ts and translations.ts file as given in the example for [component-scoped-ssr](https://github.com/sveltekit-i18n/lib/tree/master/examples/component-scoped-ssr)

Thanks @aakash14goplani, it works!
