### ISSUE TITLE
Hiding time in {{value:date}}

### ISSUE THREAD

**Issue by juanjo** [sveltekit-i18n/lib#48]
Is there any way to hide the time in a {{value:date}} in parser-default?

```js
{$t("app.modifier_date", { value: new Date(contract.starts_at) } )}
```

I am getting _Jan 4, 2022, 11:34 AM_, and what I would like to get is just _Jan 4, 2022_

Thanks in advance,
J.

**Comment by jarda-svoboda** [comment]
Ok, this should have work with setting something like this to built-in date modifier:

```svelte
{$t('content.modifier_date', { value: $now }, { date: {
    year: "numeric",
    month: "short",
    day: "2-digit",
} })}
```

but it throws an error:
`Can't set option year when dateStyle is used`

so it needs to be fixed...
