### ISSUE TITLE
Thanks for the great library, can we use it on store components

### ISSUE THREAD

**Issue by bitdom8** [sveltekit-i18n/lib#52]
Have this error :Cannot find name '$t'.ts(2304)

**Comment by bitdom8** [comment]
Found it : get(t)("Category")

Thanks

**Comment by jarda-svoboda** [comment]
Or `t.get("your.translation")`

**Comment by eikaramba** [comment]
this should be added to the readme, very useful information how to retrieve it from plain js files. sure, it is general svelte knowledge but still :)

**Comment by jarda-svoboda** [comment]
@eikaramba it’s mentioned [in the Docs](https://github.com/sveltekit-i18n/base/blob/master/docs/README.md#t-readablekey-string-vars-recordany-any--string---get-key-string-vars-recordany-any--string-).)
