### ISSUE TITLE
Single translation file per language

### ISSUE THREAD

**Issue by EskelCz** [sveltekit-i18n/lib#53]
Thanks for the library.

Is it possible to have just one file per language? I have just a few texts per page and it doesn't make much sense to have then separate files. I'd like to use a js file instead of json and separate the pages with comments.

I tried this config
```
const lang = { en: 'English', cs: 'Česky' }
export const config = {
  translations: { en: { lang }, cs: { lang } },
  loaders: [
    { locale: 'en', loader: async () => await import('./en.js') },
    { locale: 'cs', loader: async () => await import('./cs.js') }
  ]
}
```
it doesn't throw any errors but the `t` method just returns the argument string.

**Comment by jarda-svoboda** [comment]
Hi @EskelCz!

This library is meant to be module-based, so every translation "module" should have a specific `key` (so the lib can identify later which modules are already loaded). This means that you can use this config:

```js
const lang = { en: 'English', cs: 'Česky' }
export const config = {
  translations: { en: { lang }, cs: { lang } },
  loaders: [
    { locale: 'en', key: 'common', loader: async () => await import('./en.js') },
    { locale: 'cs', key: 'common', loader: async () => await import('./cs.js') }
  ]
}
```

which results in `$t('common.your.translations')` inside your `.svelte` file.

Hope this helps!.)

**Comment by EskelCz** [comment]
Perfect, thanks :)
