### ISSUE TITLE
locale-router example typo

### ISSUE THREAD

**Issue by grind-t** [sveltekit-i18n/lib#58]
Hello!
I found a typo on this [line](https://github.com/sveltekit-i18n/lib/blob/6a0d1e4a857d2016dda85d33435415be0789b1d4/examples/locale-router/src/hooks.js#L22), it should be `request.headers.get('accept-language')` instead of `request.headers['accept-language']`.
Here is a [link](https://github.com/sveltejs/kit/issues/4543) for the same issue.
Thanks for your work ❤️

**Comment by jarda-svoboda** [comment]
oh, thanks for the report!:) fixed... https://github.com/sveltekit-i18n/lib/commit/b0ff03b8ba549c0738308c44af73ead9a9c774ed
