### ISSUE TITLE
Typescript payload not inferred in "new i18n"

### ISSUE THREAD

**Issue by ikoruk** [sveltekit-i18n/lib#69]
Unless I'm missing something, `new i18n(config)` does not infer the type of `Params` from `config` so `@sveltekit-i18n/parser-default` needs to be imported just to get the `Parser` type to declare it explicitly.

For `translations.ts` I am forced to do this so that my type checking doesn't return an error:

```
import i18n from 'sveltekit-i18n';
import type { Config } from 'sveltekit-i18n';
import type { Parser } from '@sveltekit-i18n/parser-default';

export const defaultLocale = 'en';

export interface Payload extends Parser.PayloadDefault {
    placeholder?: string;
}

const config: Config<Payload> = {
   ...
};

export const { t, locale, locales, loading, loadTranslations, translations } = new i18n<
    Parser.Params<Payload>
>(config);
```

If I don't include `<Parser.Params<Payload>>`, I get an error that `placeholder` doesn't exist when passing it to a `$t(...)`.

**Comment by jarda-svoboda** [comment]
Hi @ikoruk!

That's weird... It works like this for me:
```ts
// translations.ts

import i18n from 'sveltekit-i18n';
import type { Config } from 'sveltekit-i18n';
import type { Parser } from '@sveltekit-i18n/parser-default';

export const config: Config = {};

export const { t, loading, locales, locale, loadTranslations } = new i18n<Parser.Params<{param?: number}>>(config);
```

routes/index.svelte:
<img width="962" alt="Snímek obrazovky 2022-05-15 v 18 17 56" src="https://user-images.githubusercontent.com/20700514/168483081-e9c63e13-42db-48c1-8e41-c867c65295ef.png">

What IDE do you use? Does it work in pure `ts` file using `t.get('placeholder', { param: 'value' })`?

Anyway, there is different issue regarding type exports. The `Parser` namespace should have been exported from `sveltekit-i18n` as well - just for better DX...

**Comment by ikoruk** [comment]
So you're right that `Config` doesn't actually need to be typed with the payload, but what I meant is needing to explicitly declare `i18n< Parser.Params<...>>`, which indeed leads to needing the `Parser` namespace, which means adding `@sveltekit-i18n/parser-default` to the direct dependencies...

Can't i81n infer the `Payload` in `Parser.Params<Payload>` from `Config<Payload>` ?

**Comment by ikoruk** [comment]
I am not an expert in typescript but for example instead of:
```js
declare class I18n<Params extends Parser.Params> extends Base<Params> {
    constructor(config?: Config);
    loadConfig: (config: Config) => Promise<void>;
}
```

This works for me:
```js
declare class I18n<Params extends Parser.Params<P, M>, P = Parser.PayloadDefault, M = Modifier.DefaultProps> extends Base<Params> {
    constructor(config?: Config<P, M>);
    loadConfig: (config: Config<P, M>) => Promise<void>;
}
```

That way it just needs `const config: Config<{param?: number}>` and nothing else.

**Comment by jarda-svoboda** [comment]
Oh, misunderstood the original description – just tried and you are right – it does not infer the type from `Config<{ payload: 'value' }>` even though it should...

**Comment by jarda-svoboda** [comment]
It works [here](https://github.com/sveltekit-i18n/lib/blob/master/examples/parser-default/src/lib/translations/index.ts#L10-L13), when `@sveltekit-i18n/base` and `@sveltekit-i18n/parser-default` are used separately, but it does not work under `sveltekit-i18n`, so you are 100% right with `sveltekit-i18n` declaration...
