### ISSUE TITLE
[i18n]: Non-standard locale provided:

### ISSUE THREAD

**Issue by Swepool** [sveltekit-i18n/lib#75]
Been trying to figure this one out, can't seem to find where it's coming from?
`Non-standard locale provided: 'static'. Check your 'translations' and 'loaders' in i18n config...`

**Comment by jarda-svoboda** [comment]
There is other unmentioned possibility that your locale `static` value comes from `locale.set(…)` (and not from your config). This warning should be definitely updated.. 
anyway you could use `log.level = 'debug'` config which should give you more detailed information so maybe then you could see where the wrong locale input comes from..

**Comment by Swepool** [comment]
Hmm, think it's referring to my static folder for whatever reason 🤔

**Comment by Swepool** [comment]
Hmm weird, haven't really changed anything 🤔 

https://github.com/Swepool/nbx-site

**Comment by Swepool** [comment]
debug doesn't really give me anything, but everything seems work.

**Comment by jarda-svoboda** [comment]
Ok, I’ll run it during today, but on a first look I would say there is some bad img src (or other static asset) with route-like url so it’s probably accepted [here](https://github.com/Swepool/nbx-site/blob/8eed4cedd2f66d486e46e72542a19b2e8881b94a/src/hooks.js#L12) and/or [here](https://github.com/Swepool/nbx-site/blob/8eed4cedd2f66d486e46e72542a19b2e8881b94a/src/routes/__layout.svelte#L7)

**Comment by jarda-svoboda** [comment]
i just tried and i'm not getting the warning - was it some specific page/app state?

**Comment by Swepool** [comment]
Make sure you changed the log level or remove it. It's whenever I'm switching page 🤔

**Comment by jarda-svoboda** [comment]
Ok, that's weird, but it seems that `.woff` files go through the `load` function in SvelteKit so it is recognized as a url to parse the locale from... Just tried to insert this supercool log `console.log(`lang constant in the __layout 'load' function has '${lang}' value – parsed from '${pathname}' pathname.`);` after `const lang = ...` and getting:

```ini
lang constant in the __layout 'load' function has 'static' value – parsed from '/static/fonts/basis-grotesque-bold-pro.woff' pathname.
[i18n]: Non-standard locale provided: 'static'. Check your 'translations' and 'loaders' in i18n config...

lang constant in the __layout 'load' function has 'static' value – parsed from '/static/fonts/basis-grotesque-off-white-pro.woff' pathname.
[i18n]: Non-standard locale provided: 'static'. Check your 'translations' and 'loaders' in i18n config...

lang constant in the __layout 'load' function has 'en' value – parsed from '/en/about' pathname.
// ^^^ This one is correct => no additional warnings

lang constant in the __layout 'load' function has 'static' value – parsed from '/static/fonts/basis-grotesque-regular-pro.woff' pathname.
[i18n]: Non-standard locale provided: 'static'. Check your 'translations' and 'loaders' in i18n config...
```

Not 100% sure yet, but It seems like a SvelteKit's bug to me...

**Comment by Swepool** [comment]
Interesting 🤔 hmmm... that's strange..

**Comment by R3D2** [comment]
It also prompts this message when adding a “service-worker” file in the project.

`[i18n]: Non-standard locale provided: 'service-worker.js'. Check your 'translations' and 'loaders' in i18n config...`

**Comment by jarda-svoboda** [comment]
Not tested yet, but I guess it’s probably the same issue with SvelteKit..

**Comment by kevin192291** [comment]
Hello all,
I believe the error is due to you NOT using a standard language code. An example of this would be using "jp" for Japan. The correct country abreviation is "ja".
For a full list see here: [language_codes](https://www.w3schools.com/tags/ref_language_codes.asp).
Possibly you have "static" as a language Code????

**Comment by R3D2** [comment]
```
export const defaultLocale = 'fr';

export const { t, locale, locales, loading, loadTranslations, translations } = new i18n(config);

loading.subscribe(async ($loading) => {
	if ($loading) {
		await loading.toPromise();
	}
});
```
I'm using 'en' and 'fr', which it seems to be ok.

**Comment by jarda-svoboda** [comment]
Correct me if i'm wrong, but i think that current version of SvelteKit no longer loads static assets through the `load` function, so i'm closing this issue for now..
