### ISSUE TITLE
I suggest pinning SvelteKit version to avoid breaking change error

### ISSUE THREAD

**Issue by stephane-klein** [sveltekit-i18n/lib#86]
Hello,

What do you think to pin SvelteKit version in [`examples/*`](https://github.com/sveltekit-i18n/lib/tree/master/examples) to avoid breaking change error like [this](https://github.com/sveltekit-i18n/lib/issues/85)?

Best regards,
Stéphane

**Comment by jarda-svoboda** [comment]
I would rather update the dev script to `vite dev` in examples… i think better to stay up to date and include all new features bug fixes etc..
