### ISSUE TITLE
Can Arrays be translated?

### ISSUE THREAD

**Issue by eikaramba** [sveltekit-i18n/lib#92]
I have a list of FAQ entries as an array of objects like
```
[
  {
  title:"can i do xxxxxx?"
  text:"yes you can"
  },
  .....
]
```

I wasn't able to translate this, is this possible? it would be nice if i can just create a faq.json put the array there and use it via $t('faqs').

**Comment by jarda-svoboda** [comment]
Hi.)
Currently it works like:
```jsonc
// faqs.json
{
  faqs: [
    {
      title:"can i do xxxxxx?"
      text:"yes you can"
    }
  ]
}
```

```js
// page.svelte
$t('faqs.0.title');
```

**Comment by eikaramba** [comment]
yes that works, but the problem is that i am not able to get ALL Faq entries with that approach. basically i just want to retrieve all FAQ entries and filter them based on some query. doing $t('faqs') did not work for me. should it?

**Comment by jarda-svoboda** [comment]
Ok, it’s currently not designed to work this way.. However it can be useful so I’m adding it.

**Comment by eikaramba** [comment]
wow thanks, yeah that would be great. just had another case were this would be super helpful

**Comment by Suyashtnt** [comment]
Any updates on this? I would really like to be able to do this

**Comment by BlockSpeed03** [comment]
I would really love to see this happen! I need it in projects!

**Comment by Anastasia199129** [comment]
Tell me please, has not yet appeared a function for enumeration of mvssivs?
