### ISSUE TITLE
issue with new sveltekit version

### ISSUE THREAD

**Issue by DAHNEEV** [sveltekit-i18n/lib#94]
After the changes (https://github.com/sveltejs/kit/discussions/5774) I get the error: 

> "[i18n]: No translation key or locale provided. Skipping translation...",

 in the browser console also:

> <Layout> was created with unknown prop 'data' +layout.svelte:94:92
> <Error> was created with unknown prop 'data' error.svelte:244:92
> <Error> was created with unknown prop 'errors'"

ps. I am using an example that I have adapted to the new version (https://github.com/sveltekit-i18n/lib/tree/master/examples/locale-router)

**Comment by MarcGodard** [comment]
I can confirm

**Comment by bitdom8** [comment]
Using the new sveltekit, it's all gone now https://github.com/sveltekit-i18n/lib/blob/master/examples/locale-router/src/hooks.js#L31-L35.

Hook not refers to touter/[lang]

**Comment by studylet** [comment]
I have the same problem. I don't get any translation text

**Comment by ulvidamirli** [comment]
I have the same problem. App doesn't load any translation text

**Comment by benjaminlewandowski** [comment]
@VolkerSchiewe could you create an example repo that shows that workflow?

**Comment by jarda-svoboda** [comment]
@VolkerSchiewe or preferably a PR for some of examples?.)

**Comment by frck006** [comment]
@VolkerSchiewe Can you show us your files "layout.server.ts" and "layout.ts", please ?

**Comment by jonsaw** [comment]
I tweaked my code based on the comments here. The translations will load, but as soon as the app mounts, the translations disappear (see attached video).

https://user-images.githubusercontent.com/1572333/190126490-ea729589-0895-485e-bd66-6c7ca800d1ac.mov

The only way I can get around this is to reload the translations again on mount in `+layout.svelte`.

```typescript
	onMount(() => {
		// FIXME: issue with i10n not loading properly on the frontend
		if (browser) {
			locale.set(getDocumentCookieObject()['language'] || 'en');
		}
	});
```

and comment out any scoped translations:

```typescript
		{
			locale: 'en',
			key: 'login',
			// FIXME: issue with i10n not loading in frontend
			// routes: ['/login', '/signout'],
			loader: async () => (await import('./en/login.json')).default
		},
		{
			locale: 'ms',
			key: 'login',
			// FIXME: issue with i10n not loading in frontend
			// routes: ['/login', '/signout'],
			loader: async () => (await import('./ms/login.json')).default
		},```

**Comment by jonsaw** [comment]
Ignore my previous comment. I managed to get it to work. Example [here](https://github.com/jonsaw/sveltekit-i18n-example).

Notable files to look at:

- [hook.ts](https://github.com/jonsaw/sveltekit-i18n-example/blob/main/src/hook.ts)
- [+layout.ts](https://github.com/jonsaw/sveltekit-i18n-example/blob/main/src/routes/%2Blayout.ts) (instead of +layout.server.ts)

**Comment by azzamsa** [comment]
> Ignore my previous comment. I managed to get it to work. Example [here](https://github.com/jonsaw/sveltekit-i18n-example).
> 
> Notable files to look at:
> 
>     * [hooks.server.ts](https://github.com/jonsaw/sveltekit-i18n-example/blob/main/src/hooks.server.ts)
> 
>     * [+layout.ts](https://github.com/jonsaw/sveltekit-i18n-example/blob/main/src/routes/%2Blayout.ts) (instead of +layout.server.ts)

Worked like a charm! :tada:. Thanks. Saved my day.

**Comment by stinger5** [comment]
Is there any chance to get a working example for the locale-router-static with just js and without ts? I tried to fix it like @VolkerSchiewe described, but it does not work. :(

**Comment by jonbitgood** [comment]
> Is there any chance to get a working example for the locale-router-static with just js and without ts? I tried to fix it like @VolkerSchiewe described, but it does not work. :(

Sure, here's a sample repo using the static adapter and sveltekit-i18n library. Using a local store to keep track of the users locale preference.

https://github.com/jonbitgood/Sample-Static-Sveltekit-i18n

**Comment by robots4life** [comment]
I'd love to see a detailed example for [locale-router](https://github.com/sveltekit-i18n/lib/tree/master/examples/locale-router). :heart:

**Comment by b-d-m-p** [comment]
> > Is there any chance to get a working example for the locale-router-static with just js and without ts? I tried to fix it like @VolkerSchiewe described, but it does not work. :(
> 
> Sure, here's a sample repo using the static adapter and sveltekit-i18n library. Using a local store to keep track of the users locale preference.
> 
> https://github.com/jonbitgood/Sample-Static-Sveltekit-i18n

I have the same set up as @stinger5 (locale-router-static with JS not TS), and I'm trying to user your example repo (thanks so much), but it looks so different from the main example repo (below) that I am having trouble making things work. Any suggestions?

https://github.com/sveltekit-i18n/lib/tree/master/examples/locale-router-static

**Comment by b-d-m-p** [comment]
> Ignore my previous comment. I managed to get it to work. Example [here](https://github.com/jonsaw/sveltekit-i18n-example).
> 
> Notable files to look at:
> 
>     * [hooks.server.ts](https://github.com/jonsaw/sveltekit-i18n-example/blob/main/src/hooks.server.ts)
> 
>     * [+layout.ts](https://github.com/jonsaw/sveltekit-i18n-example/blob/main/src/routes/%2Blayout.ts) (instead of +layout.server.ts)

@stinger5 I was able to get translations to appear by adding the content from these two files to mine. Add what is in hooks.server.ts to your file (remove the ts stuff), then add everything in +layout.ts to +layout.js (remove the ts stuff). 

Thanks @jonsaw!

**Comment by cupcakearmy** [comment]
> Ignore my previous comment. I managed to get it to work. Example [here](https://github.com/jonsaw/sveltekit-i18n-example).
> 
> Notable files to look at:
> 
>     * [hooks.server.ts](https://github.com/jonsaw/sveltekit-i18n-example/blob/main/src/hooks.server.ts)
> 
>     * [+layout.ts](https://github.com/jonsaw/sveltekit-i18n-example/blob/main/src/routes/%2Blayout.ts) (instead of +layout.server.ts)

Thanks! That worked like a charm!

**Comment by jarda-svoboda** [comment]
All examples have been updated to the latest version of SvelteKit so I’m closing this issue.
